name: Static analysis

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Cppcheck
      run: |
        sudo apt update
        sudo apt --yes install cppcheck

    - name: Static analysis
      run: |
        cppcheck --project=sykerolabs.cppcheck --error-exitcode=1 --enable=all
